# 本地环境配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arXiv-Daily

  data:
    redis:
      host: localhost
      port: 16379

  kafka:
    bootstrap-servers: localhost:9092

# MinIO对象存储配置
minio:
  endpoint: http://localhost:9000

# Kafka消息队列配置
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    topics:
      - arxiv-daily
      - parse-topic
